# Generated by Django 5.0.6 on 2024-07-12 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0002_usuario_delete_cliente_delete_generocli'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$HKoffQJ8sDnsRB5KhxhJkU$wVoE7AqbhJYQyoFP/CT2B5K6REBwcIroqxuTdAoCAp4=', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='default_usermane', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(blank=True, to='tiendaweb.producto')),
            ],
        ),
    ]
