# Generated by Django 5.0.6 on 2024-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0003_producto_usuario_password_usuario_username_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$zSjHR1qUIuENzj2PgWCGXz$nPDUyRu+OT4PPoJvkt/b9wM2lyaMJUZ43Q/j99KwF2g=', max_length=100),
        ),
    ]
